[package]
name = "mx-bridge-sc-sui"
edition = "2024.beta"

[dependencies]
locked_token = { git = "https://github.com/multiversx/mx-locked-token-sc-sui.git", rev = "master", subdir = "" }

[addresses]
shared_structs = "0x0"
safe_module = "0x0"
bridge_safe = "0x0"
utils = "0x0"

[dev-dependencies]
# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"
