[package]
name = "bridge_safe"
edition = "2024.beta"
version = "0.0.1"

[dependencies]
treasury = { git = "https://github.com/multiversx/stablecoin-sui.git", rev="xmn-launch", subdir = "packages/treasury", published-at = "0x28182c116f8f9a015b348f61e6330bdccdae7c192b9ba7293d4e296e912ed070"}
locked_token = { git = "https://github.com/multiversx/mx-locked-token-sc-sui.git", rev = "master", subdir = "", published-at = "0xcbcfc2873899ee4c54e16aa8e63403852001fd4587558a9371e358603189c528"}
sui_extensions = { git = "https://github.com/multiversx/stablecoin-sui.git", rev="xmn-launch", subdir = "packages/sui_extensions", override = true }
